FROM golang:1.19.1-alpine3.16 AS builder

WORKDIR /usr/src/app

COPY hello.go ./

RUN go mod init hello && \
    go build

FROM scratch
WORKDIR /exec
COPY --from=builder /usr/src/app/hello .
CMD ["/exec/hello"]
